package com.example.gameking_var2.myapplication.GPS;

import com.example.gameking_var2.myapplication.R;
import com.google.android.glass.app.Card;
import com.google.android.glass.media.Sounds;
import com.google.android.glass.widget.CardBuilder;
import com.google.android.glass.widget.CardScrollAdapter;
import com.google.android.glass.widget.CardScrollView;

import android.app.Activity;
import android.content.Context;
import android.location.Criteria;
import android.location.Location;
import android.location.LocationListener;
import android.location.LocationManager;
import android.media.AudioManager;
import android.os.Bundle;
import android.view.View;
import android.view.ViewGroup;
import android.widget.AdapterView;

import java.util.List;

/**
 * An {@link Activity} showing a tuggable "Hello World!" card.
 * <p/>
 * The main content view is composed of a one-card {@link CardScrollView} that provides tugging
 * feedback to the user when swipe gestures are detected.
 * If your Glassware intends to intercept swipe gestures, you should set the content view directly
 * and use a {@link com.google.android.glass.touchpad.GestureDetector}.
 *
 * @see <a href="https://developers.google.com/glass/develop/gdk/touch">GDK Developer Guide</a>
 */
public class GPS extends Activity  implements LocationListener {
    /**
     * {@link CardScrollView} to use as the main content view.
     */
    //private CardScrollView mCardScroller;

    /**
     * "Hello World!" {@link View} generated by .
     */
    //private View mView;
    double latitude=4.44,longitude=4.44;
    String whereme;
    @Override
    protected void onCreate(Bundle bundle) {
        super.onCreate(bundle);

        LocationManager mlocation  = (LocationManager)getSystemService(LOCATION_SERVICE);

        Criteria criteria = new Criteria();
        criteria.setAccuracy(Criteria.ACCURACY_FINE);
        criteria.setAltitudeRequired(true);
        List<String> providers = mlocation.getProviders(criteria,true);

        for(String provider : providers)
        {
            mlocation.requestLocationUpdates(provider,1000,0,GPS.this);
        }

        Card card = new Card(this);
        card.setText(String.valueOf(latitude) + "\n" + String.valueOf(longitude));

        View view = card.getView();
        setContentView(view);


    }

    public void cardd()
    {
        Card card = new Card(this);
        card.setText( whereme);

        View view = card.getView();
        setContentView(view);
    }

    @Override
    public void onLocationChanged(Location location) {
        latitude = location.getLatitude();
        longitude = location.getLongitude();

        if(latitude <= 24.149813 && latitude >= 24.149157 && longitude <= 120.683887 && longitude >= 120.683298)
        {
            whereme = "資訊大樓";
        }
        else if(latitude <= 24.149997 && latitude >= 24.149324 && longitude <= 120.683437 && longitude >= 120.682671)
        {
            whereme = "中正大樓";
        }
        else if(latitude <= 24.150154 && latitude >=  24.149734 && longitude <= 120.682756 && longitude >= 120.682199)
        {
            whereme = "活動中心";
        }
        else if(latitude <= 24.150771 && latitude >= 24.149986 && longitude <= 120.683328 && longitude >= 120.682593)
        {
            whereme = "昌明樓";
        }
        else if(latitude <= 24.150651 && latitude >= 24.150337 && longitude <= 120.684199 && longitude >= 120.683562 )
        {
            whereme = "弘業樓";
        }
        else if(latitude <= 24.150916 && latitude >= 24.150503 && longitude <= 120.684179 && longitude >= 120.683621)
        {
            whereme = "體育館";
        }
        else if(latitude <= 24.151339 && latitude >= 24.150936 && longitude <= 120.684113 && longitude >= 120.683871)
        {
            whereme = "奇秀樓 ";
        }
        else if(latitude <= 24.151794 && latitude >= 24.150615 && longitude <= 120.683172 && longitude >= 120.682586)
        {
            whereme = "翰英樓 ";
        }
        else if(latitude <= 24.151562 && latitude >= 24.150982 && longitude <= 120.682556 && longitude >= 120.681859)
        {
            whereme = "圖書館 ";
        }

        cardd();
    }

    @Override
    public void onStatusChanged(String provider, int status, Bundle extras) {

    }

    @Override
    public void onProviderEnabled(String provider) {

    }

    @Override
    public void onProviderDisabled(String provider) {

    }

}
